# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1
jobs:
  test:
    docker:
      - image: node:18.16.1-bullseye
  
    steps:
      - checkout
      - run: npm install
      - run: npm test
  
  deploy:
    docker:
      - image: node:18.16.1-bullseye
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: ./node_modules/.bin/netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --prod --dir=./build
workflows:
  newbie-react-workflow:
    jobs:
      - test
      - deploy:
          requires:
            - test