# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1
jobs:
  test:
    docker:
      - image: node:18.16.1-bullseye
  
    steps:
      - checkout
      - run: npm install
      - run: npm test
  
  deploy:
    docker:
      - image: node:18.16.1-bullseye
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm netlify:deploy
workflows:
  newbie-react-workflow:
    jobs:
      - test
      - deploy:
          requires:
            - test
